### PR TITLE
added uninstall script

### PR DESCRIPTION
**Pull request by Hulmani**
works when virtualbox and vagrant are installed via brew cask

### CODE REVIEW

**Comment by Hulmani** [comment]
Bell-app need to be signed from an identified developer in order to launch without permissions from the user.

**Comment by DrewPerlman** [comment]
@Hulmani The uninstall.sh file looks fine, but I'm not entirely sure what the other 38 file changes are for. 

Please undo those changes (I recommend using `git branch`es) and submit a different pull request with those changes if you'd like.

**Comment by Hulmani** [comment]
It has Bell-app files also.
Did you also consider that?

**Comment by DrewPerlman** [comment]
So are those "Bell-app" files the desktop shortcut for Macs?

If so, we'd like you to do a separate pull request with only those changes (this should help you with [how](http://stackoverflow.com/questions/12660839/pull-request-for-only-certain-files-commits) to do [that](http://stackoverflow.com/questions/6217156/break-a-previous-commit-into-multiple-commits), using `git rebase`, `git reset`, `git add` and such), and make this PR only have the uninstall.sh change. Also, it would be great if you named the "Bell-app" commit to something more clear (like "add Mac desktop shortcut" for example).

**Comment by Hulmani** [comment]
@dogi Please check if this pull request looks good

**Comment by dogi** [comment]
awesome

**Pull request merged**
